baseURL = "https://vincentchoqueuse.github.io/MOOC_filtrage_numerique/"
languageCode = "fr-fr"
title = "Filtrage Numérique"
theme = "course_theme"
publishDir = "docs"
sectionPagesMenu = "main"

[params]
  AuthorName = "Vincent Choqueuse"
  GitHub = "https://github.com/vincentchoqueuse/MOOC_filtrage_numerique"
  cover = "cover.jpg"
  email = "choqueuse@enib.fr"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
