baseURL = "https://vincentchoqueuse.github.io/MOOC_filtrage_numerique/"
languageCode = "fr-fr"
title = "Filtrage Numérique"
theme = "course_theme"
publishDir = "docs"

[params]
  AuthorName = "Vincent Choqueuse"
  GitHub = "spf13"
  Subtitle = "Hugo is Absurdly Fast!"
  cover = "cover.jpg"
  email = "choqueuse@enib.fr"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
